#!/usr/bin/env python3
import time as t
import colors as c
import random as r
import RPi.GPIO as GPIO

lightpins = [4,17,27,5,6,13,22,26,23,19,18,24]
bpins = [25,12,16,20,21]
gpins = [4,17,27]
rpins = [5,6,13]
cpins = [22,26,23,19,18,24]
score = 0
q = 0

GPIO.setmode(GPIO.BCM)
GPIO.setup(lightpins, GPIO.OUT)
GPIO.setup(bpins, GPIO.IN)

def mainmenu():
    print(c.green + '''
Welcome to the main menu! You have 4 options: "help", "quiz", "learn", and "list".
Type "help" to learn about the commands, and "exit" to close the program.''')

def loading():
    for count in range(3):
        print(c.clear + c.magenta + 'Loading |')
        t.sleep(.3)
        print(c.clear + c.magenta + 'Loading /')
        t.sleep(.3)
        print(c.clear + c.magenta + 'Loading -')
        t.sleep(.3)
        print(c.clear + c.magenta + 'Loading \\')
        t.sleep(.3)

def learnwelcome():
    print(c.green + '''
    Welcome to the Learn page! Time to learn about the French Revolution.
    Type "help" to learn about the commands.''')

def quizhelp():
    print(c.clear + c.green + '''
    Quiz game help:  You are being scored. If you don't know the answer, press the yellow button.
    You enter your answer by pushing the button for your answer. Buttons top to bottom: A, B, C, D, IDK    
    Notes: True/False questions can be answered as A meaning "true" and B meaning "false". You also have 20 
    seconds to answer each question, once you have read it. Please only push the button once. Push enter to begin.''')

def correct():
    print(c.green + '''
    CORRECT!''')
    for count in range(3):
        GPIO.output(gpins, 1)
        t.sleep(.4)
        GPIO.output(gpins, 0)

def wrong():
    print(c.red + '''
    WRONG!''')
    for count in range(3):
        GPIO.output(rpins, 1)
        t.sleep(.2)
        GPIO.output(rpins, 0)

print(c.clear + c.green + '''
Hello! Welcome to Ryan Densmore's Quiz game on the French Revolution!
Opening...''')
t.sleep(6.5)
loading()
print(c.clear)
mainmenu()

while True:
    main = input(c.green + '> ' + c.yellow).strip().lower()
    if main == 'help':
        print(c.green + '''
        Welcome to the Help page! Time to learn about the commands. "help" just brings you to this page.
        When you use the command "quiz" from the main menu, you start the Quiz Game. If you use the command
        "learn" from the main menu, you will open the program that teaches you about the French Revolution.
        Type "list" to show a list of commands you can use. "exit" does differrent things, usually said on the welcome text.
        "clear" clears the screen so it doesn't look so messy. NOTE: All commands are lowercase.''')
        mainmenu()    

    elif main == 'quiz':
        q = 0
        print(c.green + '''
    So you think you are ready to play the quiz game? Have you studied the French Revolution?''')
        quizconfirm = input(c.green + 'y/n> ' + c.yellow).strip().lower()
        if 'y' in quizconfirm:
            print(c.green + 'Much Yays! Starting quiz game.')
            t.sleep(2.5)
            print(c.clear)
            quizhelp()
            quizstart = input(c.green + '> ' + c.yellow)
            if quizstart == '':
                print(c.green + 'Great!')
                t.sleep(1)
                print(c.clear)
                

                print(c.green + '''
Q1: Who was the king of France during the revolution?
A: King Henry VIII
B: King Tut
C: King George III
D: King Louis XVI''')
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(20) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(12) == False or GPIO.input(16) == False:
                        wrong()
                        print(c.green + '''
    The right answer is D: King Louis XVI''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is D: King Louis XVI''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is D: King Louis XVI''')
                    t.sleep(.1)


                print(c.green + '''
Q2: Who was the queen of France during the revolution?
A: Queen Elizabeth II
B: Queen Hatshepsut
C: Queen Marie Antoinette
D: Queen Victoria''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(16) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(12) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The right answer is C: Queen Marie Antoinette''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is C: Queen Marie Antoinette''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is C: Queen Marie Antoinette''')
                    t.sleep(.1)


                print('''
Q3: Which is one of the causes of the revolution?
A: The king gave free food to the entire country
B: The king brought France deep into debt
C: Thomas Jefferson became king of France, but the people didn't like him
D: The king and queen got divorced, and the people were mad''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(12) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(16) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The right answer is B: The king brought France deep in debt''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is B: The king brought France deep in debt''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is B: The king brought France deep in debt''')


                print('''
Q4: Which choice explains the Reign on Terror during the revolution?
A: Napoleon attacked villages, inprisoning everyone
B: The king beheaded over 40,000 people because they were helping the revolution
C: Robespierre and the Committee of Public Saftey beheaded anyone who they they thought were "enemies of the revolution"
D: George Washington went crazy and bombarded France for 3 years''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(16) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(12) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The right answer is C: Robespierre and the Committee of Public Saftey beheaded anyone who they thought were "enemies of the revolution"''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is C: Robespierre and the Committee of Public Saftey beheaded anyone who they thought were "enemies of the revolution"''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is C: Robespierre and the Committee of Public Saftey beheaded anyone who they thought were "enemies of the revolution"''')


                print('''
Q5: True or False: The French Estates are essentialy social classes.
A: True
B: False''')
                q = 0
                t.sleep(3)
                for count in range(200):
                    if GPIO.input(25) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(12) == False:
                        wrong()
                        print(c.green + '''
    The right answer is A: True''')
                        q = 1
                    elif GPIO.input(16) == False or GPIO.input(20) == False:
                        print(c.green + '''
    That is not a choice. Please answer the question with either A or B.''')
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is A: True''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is A: True''')


                print('''
Q6: What did the revolutionary people want for France?
A: More rights for the Third Estate
B: A new king
C: More rights for the First Estate
D: More taxes so France could buy food''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(25) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(12) == False or GPIO.input(16) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The right answer is A: More rights for the Third Estate''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is A: More rights for the Third Estate''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is A: More rights for the Third Estate''')


                print('''
Q7: Why was the storming of the Bastille fortress important to the revolution?
A: It was Napoleon's first victory
B: The king happened to be at the fort, and the people beheaded him
C: The people freed dangerous people from prisons there
D: The people got weapons and the king realized he had lost control of the people''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(20) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(12) == False or GPIO.input(16) == False:
                        wrong()
                        print(c.green + '''
    The right answer is D: The people got weapons and the king realized he had lost control of the people''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is D: The people got weapons and the king realized he had lost control of the people''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is D: The people got weapons and the king realized he had lost control of the people''')



                print('''
Q8: Which document did the National Assembly adopt right after they formed, and tryed to uphold throughout the revolution?
A: The Declaration of Independence
B: The Declaration of the Rights of Man and Citizen
C: The Constitution
D: The Bill of Rights''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(12) == False:
                        correct()
                        score += 1
                        q = 1
                elif GPIO.input(25) == False or GPIO.input(16) == False or GPIO.input(20) == False:
                    wrong()
                    print(c.green + '''
    The right answer is B: The Declaration of the Rights of Man and Citizen''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is B: The Declaration of the Rights of Man and Citizen''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is B: The Declaration of the Rights of Man and Citizen''')


                print('''
Q9: Fill in the missing word. The French Revolution brought France from a monarchy all the way to a ___________.
A: Monarchy
B: Democracy
C: Communist Society
D: Oligarchy''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(25) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(12) == False or GPIO.input(16) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The right answer is A: Monarchy''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is A: Monarchy''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is A: Monarchy''')


                print('''
Q10: How did the revolution affect the world?
A: It was the last revolution, so it didn't affect the wrold at all
B: It wasn't the first or the last revolution, but didn't affect the wrold at all
C: It gave inspiration to Hati and Spain's lands in South America
D: It gave inspiration to America for their revolution''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(16) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(12) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The right answer is C: It gave inspiration to Hati and Spain's lands in South America''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is C: It gave inspiration to Hati and Spain's lands in South America''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is C: It gave inspiration to Hati and Spain's lands in South America''')
    
    
                print('''
Q11: Which revolution{s} did the French people get inspiration from for their revolution?
A: It was the first revolution, so it didn't get inspiration from another revolution at all
B: The American revolution, because the French helped and it was successful, the people thought they could do it too.
C: It was the last revolution, so it got inspiration from all the revolutions before it.
D: The Haitian and Latin~American Revolutions because they were successful.''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(12) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(16) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The correct answer is B: The American revolution, because the French helped and it was successful, 
    the people thought they could do it too.''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The correct answer is B: The American revolution, because the French helped and it was successful, 
    the people thought they could do it too.''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The correct answer is B: The American revolution, because the French helped and it was successful, 
    the people thought they could do it too.''')
    
    
                print('''
Q12: About how many citizens were killed during the Reign of Terror?
A: 7
B: 40,000
C: 5,000
D. 400,000,000,000''')
                q = 0
                t.sleep(5)
                for count in range(200):
                    if GPIO.input(12) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(25) == False or GPIO.input(16) == False or GPIO.input(20) == False:
                        wrong()
                        print(c.green + '''
    The right answer is B: 40,000''')
                        q = 1
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is B: 40,000''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is B: 40,000''')
    
    
                print('''
Q13: True or False: One of the things the Declaration of the Rights of Man and Citizen considered
     most precious was freedom of speech.
A: True
B: False''')
                q = 0
                t.sleep(4)
                for count in range(200):
                    if GPIO.input(25) == False:
                        correct()
                        score += 1
                        q = 1
                    elif GPIO.input(12) == False:
                        wrong()
                        print(c.green + '''
    The right answer is A: True''')
                        q = 1
                    elif GPIO.input(16) == False or GPIO.input(20) == False:
                        print(c.green + '''
    That is not a choice. Please answer the question with either A or B.''')
                    elif GPIO.input(21) == False:
                        print(c.green + '''
    The right answer is A: True''')
                        q = 1
                    t.sleep(.1)
                if q == 0:
                    print(c.green + '''
    The right answer is A: True''')


   

            else:
                print(c.red + 'Uh Oh! You broke the program! Type "quiz" to restart.')
        elif 'n' in quizconfirm:
            print(c.green + 'Ok. See you later!')
        else:
            print(c.red + 'Uh Oh! You broke the program! Type "quiz" to fix the issue.')
        

    elif main == 'learn':
        print(c.clear)
        learnwelcome()
        while True:
            learn = input(c.green + '> ' + c.yellow).strip().lower()

            if learn == 'help':
                print(c.green + '''
    Welcome to the Help page! Time to learn about the commands. "help" brings you to this page. When you
    use the command "list", you can see all of the commands you can currently run. Typing "exit" exits the program, and "clear"
    cleans up the screen. Some more commands:    "summary" - a summary of the French Revolution    "dates" - Major dates of the 
    French Revolution    "events" - events of the revolution    "timeline1" - a timeline of the revolution, part 1    "timeline2" - a
    timeline of the revolution, part 2    "people" - major people of the revolution    "inventions" - some new inventions that were 
    made during the revoulution.    Using the command "quiz" tells you how to start the quiz game, when you are ready, and "sources" 
    lists my sources of my information. NOTE: All commands are lowercase.''')

            elif learn == 'list':
                print(c.green + '''
    The commands you can currently run are:
    - help
    - list
    - exit
    - clear
    - summary
    - dates
    - events
    - timeline1
    - timeline2
    - people
    - inventions
    - quiz
    - sources''')

            elif learn == 'exit':
                exit()
           
            elif learn == 'clear':
                print(c.clear)
                learnwelcome()

            elif learn == 'summary':
                print(c.green + 'A brief summary of the revolution.')
                print(c.green + '''
    The revolution pretty much started with King Louis XVI bringing the country into lots of debt and starving, along with his bad
    leadership skills. He called a meeting of the Estates General, and locked out the 3rd Estate, who then decide to form the 
    National Assembly on the King's tennis courts. The people storm the Bastille fortress, and gain weapons other than torches and
    pitchforks. The National Assembly adopts the Declaration of the Rights of Man and Citizen to try and declare independence from 
    the monarchy. French women come to the royal palace of Versailles and demand the king and queen return to paris; eventually,
    they try to flee but are caught. The Legislative Assembly is formed, and a year later France becomes the Republic of France.
    King Louis XVI is tried and executed, then the Committee of Public Saftey is created and the Reign of Terror begins, with 
    Robespierre leading them in beheading thousands of citizens. The wife of King Louis XVI, Marie Antoinette, is executed, and 
    Robespierre becomes the leader of the Convention, which is now the governing body of France. About a month later, he and his
    followers are beheaded and the Convention and Committee of Public Saftey are replaced by the Thermidorian Convention, who 
    adopts a new constitution. The Directory is now the governing body of France. Eventually, the famous French general Napoleon
    declares himself emperor of France, and this is the end of the revolution. France went all the from a monarchy...
    back to a monarchy. Yay!''')

            elif learn == 'dates':
                print(c.green + 'And now, some of the major dates of the French Revolution.')
                print(c.green + 'Please note, these dates, in a shorter form, will be in the timeline.')
                print('''
    - The enitire revolution was 1789 - 1799.
    
    - June, 1789: The National Assembly has begun, with the representitives of the Third Estate taking the Tennis Court Oath.
    - July, 1789: The storming of the Bastille, a French fortress.
    - August, 1789: The National Assembly adopts "The Declaration of the Rights of Man and Citizen", which is
      essentialy their declaration of independence from the throne.
    - October, 1789: French women march on to the palace of Versailles and demand that the royal family return to Paris.
    
    - June, 1791: The royal family tries to flee France, but is caught.
    - October, 1791: The Legislative Assembly is formed.
    
    - April, 1792: France declares war on Austria and Prussia.
    - September, 1792: France is declared "The Republic of France".
    - December, 1792: King Louis XVI's trial begins.
    
    - January, 1793: King Louis XVI is executed.
    - February, 1793: France declares war on England and The Netherlands.
    - April, 1793: The Committee of Public Safety is created.
    - July, 1793: Maximilien Robespierre becomes the leader of the Committee of Public Safety.
    - September, 1793: The Reign of Terror begins. Robespierre and the Committee of Public Saftey are massacring citizens, deeming them
      "enemies of the revolution" and beheading them with the Guillotine, a new invention.
    - October, 1793: King Louis XVI's wife, Queen Marie Antoinette, is executed.
    - December, 1793: France has victory in it's war with Western Europe.
    
    - June, 1794: Robespierre is elcted President of the Convention.
    - July, 1794: The Reign of Terror ends! Robespierre and his followers are arrested and beheaded. The Convention and Committee of Public Saftey 
      are replaced by the Thermidorian Convention.

    - 1795: France continues to have victories
    - August, 1795: France adopts a new constitution
    - October, 1795: The Directory becomes the new government group who rule France.

    - March to May, 1796: Napoleon is General of France's army and has lots of success throughout Europe.

    - December, 1798: England, Russia, and Italy sign a pact against France.

    - November, 1799: Napoleon takes over the Directory and declares himself Emperor of France. End of Revolution.
    Type "clear" to clear the screen.''')

            elif learn == 'events':
                print(c.green + 'Some major events of the French Revolution:')
                print(c.green + '''
    - June, 1789: National Assembly formed by the Tennis Court Oath
    - July, 1789: Storming of the Bastille
    - August, 1789: Adoption of "The Declaration of the Rights of Man and Citizen"
    - October, 1791: The Legislative Assembly is formed.
    - September, 1792: France is declared a republic.
    - January, 1793: King Louis XVI is executed.
    - September, 1793: The Reign of Terror begins.
    - June, 1794: Robespierre, the leader of the Committee of Public Saftey, becomes leader of France.
    - July, 1794: Robespierre and his followers are executed, and the Committee of Public Saftey and Convention are replaced by the
      Thermidorian Convention.
    - August, 1795: France adopts a new constitution
    - October, 1795: The Directory is the new leadership group of France.
    - November, 1799: Napoleon declares himself Emperor of France; end of revoltuion.''')

            elif learn == 'timeline1':
                print(c.green + '''
    Hopefully, a decent timeline of the dates in the "dates" command. Notes:
    - Some months will be shortened to show that there are no events during that month.
    - This is part 1; type "timeline2" for part 2 of the timeline.
    - There might be abbrieviations, such as "Assmbly", which means "Assembly", and "Con." meaning "Convention".

    1789:
  January February March April May June             July          August          September October                         November December
     |        |      |     |    |    |     *         |    *          |        *      |          |   *                  *        |      | |
     |--------|------|-----|----|----|-----|---------|----|----------|--------|------|----------|---|------------------|--------|------|-|
     |        |      |     |    |    |   3rd Estate  |    Fall of    |Assembly adopts|          |Women march to  Assembly is    |      | |
                                       declares itself    Bastille  Declaration of the       Versailles; demand  installed in 
                                       National Assembly          Rights of Man and Citizen  royal family return     Paris
                                                                                                to Paris

    1790:
  January February March April May June July August September      October November December
     |        |      |     |    |    |   |      |      |               |       |      |      |
     |--------|------|-----|----|----|---|------|------|----------|----|-------|------|------|
     |        |      |     |    |    |   |      |      | Tricolor made |       |      |      |
                                                         national flag

    1791:
  January February March April May June             July August September      October         November December
     |        |      |     |    |    |               |      |      |               |               |      |      |
     |--------|------|-----|----|----|--------|------|------|------|-|-------------|-|-------------|------|------|
     |        |      |     |    |    | Royal family  |      |      |Nationa Assmbly| Legislative   |      |      |
                                 tries to escape France;     votes on constitution;  Assmbly formed.
                                     they are caught         accepted by king later

    1792:
  January February March April            May June July August          September                October November December
     |        |      |     |               |    |   |      |               |                         |       |      |                |
     |--------|------|-----|-----------|---|----|---|------|----------|----|---------|-----------|---|-------|------|-------|--------|
     |        |      |     |France declares|    |   |      |People invade  |Legislative    France    |       |      | Trial of King  |
                       war on Austria and Prussia     palace and take royal  Assmbly      declared                  Louis XVI begins
                                                          family hostage   becomes Con.,    Republic of France
                                                                         monarchy abolished.

    1793:
  January        February          March April            May June July          August September      October         November December
     |               |               |     |               |    |   |               |      |               |               |      |      |
     |-------|-------|-|-------------|-----|---|-----------|----|---|-----------|---|------|---|-----------|---------|-----|------|------|
     |Execution of   |France declares|     |Committee of   |    |   |Robespierre is |      |Reign of Terror|  Execution of |      |      |
   King Louis XVI   war on England and  Public Safety created   leader of Committee of          begins      Marie Antoinette
                      The Netherlands                                Public Saftey

Remember - type "clear" to clean the screen when you are done!
''')
            elif learn == 'timeline2':
                print(c.green + '''
    Part 2 of the timeline. Notes:
    - Some months will be shortened to show that there are no events during that month.
    - This is part 2 of the timeline; type "timeline1" for part 1.
    - Some things will be abbreviated, such as "Con." meaning "Convention" and "CPS" meaning "Committee of Public Saftey".  

    1794:
  January February March April May June             July           August September October November December
     |        |      |     |    |    |               |                |      |          |       |      |      |
     |--------|------|-----|----|----|--|------------|----------|-----|------|----------|-------|------|------|
     |        |      |     |    |    |Robespierre    |Robespierre     |      |          |       |      |      |
                        elected President of the Con. caught, beheaded.
                                                       Con./CPS replaced
                                                    with Thermidorian Con. 

    1795:
  January February March April May June July August          September October           November December
     |        |      |     |    |    |   |      |               |          |                 |      |      |
     |--------|------|-----|----|----|---|------|---------|-----|----------|---------|-------|------|------|
     |        |      |     |    |    |   |      | France adopts |          |Directory becomes|      |      |
                                                new constitution         governing body of France

    1796:
  January February March April May June July August September October November        December
     |        |      |     |    |    |   |      |      |          |       |             |      |
     |--------|------|-----|----|----|---|------|------|----------|-------|------|------|------|
     |        |      |     |    |    |   |      |      |          |       |Napoleon beat|      |
                                                                        Austrians in battle

    1797:
  January February March April May June July August September October November December
     |        |      |     |    |    |   |      |      |          |       |      |      |
     |--------|------|-----|----|----|---|------|------|----------|-------|------|------|
     |        |      |     |    |    |   |      |      |          |       |      |      |

    1798:
  January February March April May June July August September October November December
     |        |      |     |    |    |   |      |      |          |       |      |               |
     |--------|------|-----|--- |----|---|----- |----- |----------|-------|------|------------|--|
     |        |      |     |    |    |   |      |      |          |       |      |Emgland,Russia,|
                                                                          Italy sign pact against France

    1799:
  January February March April May June July August September October           November            December
     |        |      |     |    |    |   |      |      |          |                 |                 |      |
     |--------|------|-----|----|----|---|------|------|----------|-------|---------|-------|---------|------|
     |        |      |     |    |    |   |      |      |          |Napolean returns |Napoleon declares|      |
                                                  to France, leaving armies in Egypt  himself Emperor of
                                                                                     France, end of revolution.

''')
   
            elif learn == 'people':
                print(c.green + 'Important people of the French Revolution:')
                print(c.green + '''
    - King Louis XVI: The King of France during the revolution. He was tried in December, 1792 and executed a 
      month later. He married Marie Antoinette when she was 15 years old. He got the country deep in debt, and
      called a meeting of the "Estates General" to try and fix the debt. He was born in 1754.

    - Marie Antoinette: Born in 1755, she was the Queen of France during the Revolution. She married Louis XVI at age 15. She was
      executed after her husaband, in October, 1793. She is said to have told all the poor and starving people who couldn't afford
      bread "Let them eat cake!". 

    - Maximilian Robespierre: Leader of the Committee of Public Saftey and eventually the Convention, Robespierre led the Reign of 
      Terror, during which he beheaded over 30,000 people, deeming them "enemies of the revolution". However, in July, 1794, he was
      beheaded himself because he was mercilessly killing tens of thousands of people.

    - Napoleon Bonaparte: Born August, 1769, Napoleon might be one of the world's best military leaders. He got his chance right
      after the end to the Reign of Terror and the Committee of Public Saftey. He was the greatest general in France, and won
      victories against Austria, Europe, and other places. He also stopped some rebellions that were for the monarchy in France,
      and expanded the French Empire a good deal. Unfortunetly for him, he also got defeated a couple of times. He became the first
      emperor of France. He died on the island St. Helena after being exiled there.''')

            elif learn == 'inventions':
                print(c.green + 'Some devices and things created during the revolution, that had a role in it.')
                print(c.green + '''
    -  Guillotine: a device for beheading; got a lot of use during the Reign of Terror.
    - The Metric system of measurement: created by Napoleon, and used almost everywhere today.''')

            elif learn == 'quiz':
               print(c.green + 'To start the Quiz game, please restart the program by typing "exit" then "./project", then start the quiz with "quiz".')

            elif learn == 'sources':
               print(c.green + 'My sources:')
               print('''
    - mtholyoke.edu/courses/rschwart/hist255/kat_anna/timeline.html
    - sites.google.com/a/ucps.k12.nc.us/mrms-7th-grade-social-studies-textbook/the-french-revolution/important-figures-of-the-french-revolution
    - biography.com/people/napoleon-9420291
    - My Social Studies notebook''')
            else:
                print(c.red + 'Invalid Command! Try "list".')

    elif main == 'list':
        print(c.green + '''
    The commands you can currently run are:
    - help
    - quiz
    - learn
    - list
    - exit
    - clear''')

    elif main == 'exit':
        exit()

    elif main == 'clear':
        print(c.clear)
        mainmenu()

    else:
        print(c.red + 'Invalid Command! Try "list".')
