#!/usr/bin/env python3
import time as t
import colors as c
import random as r
import espeak as e
import RPi.GPIO as GPIO

 
lightpins = [4,17,27,5,6,13,22,26,23,19,18,24]
bpins = [25,12,16,20,21]
gpins = [4,17,27]
rpins = [5,6,13]
cpins = [22,26,23,19,18,24]
score = 0

GPIO.setmode(GPIO.BCM)
GPIO.setup(lightpins, GPIO.OUT)
GPIO.setup(bpins, GPIO.IN)

def mainmenu():
    print(c.green + '''
Welcome to the main menu! You have 4 options: "help", "quiz", "learn", and "list".
Type "help" to learn about the commands, and "exit" to close the program.''')

def loading():
    for count in range(3):
        print(c.clear + c.magenta + 'Loading |')
        t.sleep(.3)
        print(c.clear + c.magenta + 'Loading /')
        t.sleep(.3)
        print(c.clear + c.magenta + 'Loading -')
        t.sleep(.3)
        print(c.clear + c.magenta + 'Loading \\')
        t.sleep(.3)

def learnwelcome():
    print(c.green + '''
    Welcome to the Learn page! Time to learn about the French Revolution.
    Type "help" to learn about the commands.''')


print(c.clear + c.green + '''
Hello! Welcome to Ryan Densmore's Quiz game on the French Revolution!
Opening...''')
t.sleep(6.5)
loading()
print(c.clear)
mainmenu()

while True:
    main = input(c.green + '> ' + c.yellow)
    if main == 'help':
        print(c.green + '''
        Welcome to the Help page! Time to learn about the commands. "help" just brings you to this page.
        When you use the command "quiz" from the main menu, you start the Quiz Game. If you use the command
        "learn" from the main menu, you will open the program that teaches you about the French Revolution.
        Type "list" to show a list of commands you can use. "exit" does differrent things, usually said on the welcome text.
        "clear" clears the screen so it doesn't look so messy. NOTE: All commands are lowercase.''')
        mainmenu()    

    elif main == 'quiz':
        print(c.green + 'Welcome to the Quiz Game! Before you play, make sure you have learned about the French Revolution!')

    elif main == 'learn':
        print(c.clear)
        learnwelcome()
        while True:
            learn = input(c.green + '> ' + c.yellow)

            if learn == 'help':
                print(c.green + '''
    Welcome to the Help page! Time to learn about the commands. "help" brings you to this page. When you
    use the command "list", you can see all of the commands you can currently run. Typing "exit" exits the program, and "clear"
    cleans up the screen. Some more commands:    "summary" - a summary of the French Revolution    "dates" - Major dates of the 
    French Revolution    "events" - events of the revolution    "timeline" - a timeline of the revolution    "people" - major people 
    of the revolution    "inventions" - some new inventions that were made during the revoulution.    Using the command "quiz" tells
    you how to start the quiz game, when you are ready, and "sources" lists my sources of my information. 
    NOTE: All commands are lowercase.''')

            elif learn == 'list':
                print(c.green + '''
    The commands you can currently run are:
    - help
    - list
    - exit
    - clear
    - summary
    - dates
    - events
    - timeline
    - people
    - inventions
    - quiz
    - sources''')

            elif learn == 'exit':
                exit()
           
            elif learn == 'clear':
                print(c.clear)
                learnwelcome()

            elif learn == 'summary':
                print('yay')

            elif learn == 'dates':
                print(c.green + 'And now, some of the major dates of the French Revolution.')
                print(c.green + 'Please note, these dates, in a shorter form, will be in the timeline.')
                print('''
    - The enitire revolution was 1789 - 1799.
    
    - June, 1789: The National Assembly has begun.
    - July, 1789: The storming of the Bastille, a French fortress.
    - August, 1789: The National Assembly adopts "The Declaration of the Rights of Man and Citizen", which is
      essentialy their declaration of independence from the throne.
    - October, 1789: French women march on to the palace of Versailles and deman that the royal family return to Paris.
    
    - June, 1791: The royal family tries to flee France, but is caught.
    - October, 1791: The Legislative Assembly is formed.
    
    - April, 1792: France declares war on Austria and Prussia.
    - September, 1792: France is declared "The Republic of France".
    - December, 1792: King Louis XVI's trial begins.
    
    - January, 1793: King Louis XVI is executed.
    - February, 1793: France declares war on England and The Netherlands.
    - April, 1793: The Committee of Public Safety is created.
    - July, 1793: Maximilien Robespierre becomes the leader of the Committee of Public Safety.
    - September, 1793: The Reign of Terror begins. Robespierre and the Committee of Public Saftey are massacring citizens, deeming them
      "enemies of the revolution" and bheading them with the Guillotine, a new invention.
    - October, 1793: King Louis XVI's wife, Queen Marie Antoinette, is executed.
    - December, 1793: France has victory in it's war with Western Europe.
    
    - June, 1794: Robespierre is elcted President of the Convention.
    - July, 1794: The Reign of Terror ends! Robespierre and his followers are arrested and beheaded. The Convention and Committee of Public Saftey are replaced by the Thermidorian Convention.

    - 1795: France continues to have victories

    - March to May, 1796: Napoleon is General of France's army and has lots of success throughout Europe.

    - December, 1798: England, Russia, and Italy sign a pact against France.

    - November, 1799: Napoleon takes over the Directory and declares himself Emperor of France. End of Revolution.
    Type "clear" to clear the screen.''')

            elif learn == 'events':
                print('yay')

            elif learn == 'timeline':
                print('yay')
   
            elif learn == 'people':
                print('yay')

            elif learn == 'inventions':
                print('yay')
 
            elif learn == 'quiz':
               print(c.green + 'To start the Quiz game, please restart the program by typing "exit" then "./project".')

            elif learn == 'sources':
               print(c.green + 'My sources:')
               print('''
    - mtholyoke.edu/courses/rschwart/hist255/kat_anna/timeline.html
    -''')
            else:
                print(c.red + 'Invalid Command! Try "list".')

    elif main == 'list':
        print(c.green + '''
    The commands you can currently run are:
    - help
    - quiz
    - learn
    - list
    - exit
    - clear''')

    elif main == 'exit':
        exit()

    elif main == 'clear':
        print(c.clear)
        mainmenu()

    else:
        print(c.red + 'Invalid Command! Try "list".')
