#!/usr/bin/env python3
import RPi.GPIO as GPIO

GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
list = (4, 17, 27, 22, 5, 6, 13, 19, 26, 18, 23, 24, 25, 12, 16, 20, 21)
GPIO.setup(list, GPIO.OUT)
GPIO.output(list, 0)
